# where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data

# handling reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# filtering content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# plugins
whitelist: []
gems:      []

# conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""

# outputting
timezone:  null
quiet:    false

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/

# markdown processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include: ['_pages']

collections:
  about:
    output: false
  partners:
    output: false
  links:
    output: false
  workshops:
    output: true
  events:
    output: true
